FROM golang:1.20 as backend_compiler
WORKDIR /src/
COPY . /src/
RUN go build ./cmd/webapi

FROM debian:stable
WORKDIR /backend_binary/
COPY --from=backend_compiler /src/webapi .
EXPOSE 3000
CMD ["./webapi"]
